// Embeds the current faculty CSV as src/data/bundledSchedule.js so the app
// can offer "Użyj aktualnego planu" without an upload.
// Usage: node app/scripts/embed-csv.mjs "<path to csv>" [as-of date, e.g. 05.10.2026]
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { basename, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const [, , csvPath, asOf] = process.argv;
if (!csvPath) {
  console.error('Podaj ścieżkę do pliku CSV.');
  process.exit(1);
}
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const text = readFileSync(csvPath, 'utf8').replace(/^﻿/, '');
const fileName = basename(csvPath);
// Default "as of" comes from the export's own stamp in the header row (dd.mm.yyyy).
const stamp = asOf ?? /(\d{2}\.\d{2}\.\d{4})/.exec(text.split('\n', 5).join('\n'))?.[1] ?? '';

const out = `// Generated by scripts/embed-csv.mjs from ${fileName}. Do not edit by hand.
export const BUNDLED_FILE_NAME = ${JSON.stringify(fileName)};
export const BUNDLED_AS_OF = ${JSON.stringify(stamp)};
export const BUNDLED_CSV = ${JSON.stringify(text)};
`;
mkdirSync(join(root, 'src/data'), { recursive: true });
writeFileSync(join(root, 'src/data/bundledSchedule.js'), out);
console.log(`src/data/bundledSchedule.js written (${fileName}, stan ${stamp})`);
